import type { Pet } from "@/components/PetCard";

export const mockPets: Pet[] = [
  {
    id: "loki",
    name: "Loki",
    species: "Perro",
    breed: "Poodle",
    color: "Blanco",
    status: "lost",
    location: "Norte de Antofagasta",
    date: "Hace 1 dia",
    image: "/pets/loki.jpg",
    sightings: 0,
    reward: "$100.000",
    contactName: "Fernanda Castillo",
    contactPhone: "+56937539573",
  },
  {
    id: "balu",
    name: "Balú",
    species: "Perro",
    breed: "Poodle mestizo",
    color: "Blanco y negro",
    status: "lost",
    location: "Antofagasta",
    date: "Hace 2 dias",
    image: "/pets/balu.jpg",
    sightings: 1,
    contactName: "Jean Castillo",
    contactPhone: "+56926016629",
  },
  {
    id: "koky",
    name: "Koky",
    species: "Perro",
    breed: "Bulldog Inglés",
    color: "Fawn",
    status: "lost",
    location: "Antofagasta",
    date: "Hace 3 dias",
    image: "/pets/koky.jpg",
    sightings: 2,
    reward: "$150.000",
  },
  {
    id: "1",
    name: "Luna",
    species: "Perro",
    breed: "Golden Retriever",
    color: "Dorado",
    status: "lost",
    location: "Providencia, Santiago",
    date: "Hace 2 dias",
    image: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=450&fit=crop",
    sightings: 3,
    reward: "$50.000",
  },
  {
    id: "2",
    name: "Michi",
    species: "Gato",
    breed: "Siames",
    color: "Crema con cafe",
    status: "found",
    location: "Nunoa, Santiago",
    date: "Hace 5 horas",
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=450&fit=crop",
    sightings: 1,
  },
  {
    id: "3",
    name: "Rocky",
    species: "Perro",
    breed: "Bulldog Frances",
    color: "Atigrado",
    status: "lost",
    location: "Las Condes, Santiago",
    date: "Hace 1 dia",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=450&fit=crop",
    sightings: 7,
    reward: "$100.000",
  },
  {
    id: "4",
    name: "Canela",
    species: "Perro",
    breed: "Mestizo",
    color: "Cafe",
    status: "reunited",
    location: "Vitacura, Santiago",
    date: "Hace 3 dias",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=450&fit=crop",
    sightings: 12,
  },
  {
    id: "5",
    name: "Simba",
    species: "Gato",
    breed: "Naranja domestico",
    color: "Naranja",
    status: "lost",
    location: "La Florida, Santiago",
    date: "Hace 6 horas",
    image: "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=600&h=450&fit=crop",
    sightings: 2,
  },
  {
    id: "6",
    name: "Kiwi",
    species: "Ave",
    breed: "Canario",
    color: "Amarillo",
    status: "lost",
    location: "Macul, Santiago",
    date: "Hace 1 semana",
    image: "https://images.unsplash.com/photo-1522858547137-f1dcec554f55?w=600&h=450&fit=crop",
    sightings: 0,
  },
];

export const successStories = [
  {
    id: "s1",
    petName: "Max",
    ownerName: "Camila Rodriguez",
    days: 12,
    city: "Santiago",
    quote: "Gracias a VuelveACasa, un vecino vio a Max a 3 cuadras de mi casa. No lo podia creer cuando lo abrace de nuevo.",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    petImage: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=200&h=200&fit=crop",
  },
  {
    id: "s2",
    petName: "Mia",
    ownerName: "Sebastian Torres",
    days: 5,
    city: "Valparaiso",
    quote: "Mia se escapo durante los fuegos artificiales de Ano Nuevo. La comunidad de VuelveACasa me ayudo a encontrarla en solo 5 dias.",
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    petImage: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=200&h=200&fit=crop",
  },
  {
    id: "s3",
    petName: "Thor",
    ownerName: "Valentina Munoz",
    days: 21,
    city: "Concepcion",
    quote: "21 dias buscando a Thor. Un avistamiento en el mapa interactivo nos llevo directamente hasta el. Esta plataforma salva vidas.",
    image: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=400&fit=crop",
    petImage: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=200&h=200&fit=crop",
  },
];

export const stats = [
  { label: "Mascotas reunidas", value: 2847, suffix: "+" },
  { label: "Usuarios activos", value: 15200, suffix: "+" },
  { label: "Avistamientos reportados", value: 43600, suffix: "+" },
  { label: "Ciudades cubiertas", value: 128, suffix: "" },
];
